#!/usr/bin/env python3
"""Build-time script: parse vendored UTS #39 confusables.txt and emit a
Python module with CONFUSABLES_MAP: dict[str, str].

Usage:
    python scripts/generate_confusables.py

Reads  : data/uts39/confusables.txt  (vendored, never fetched at runtime)
Reads  : data/uts39/VERSION
Writes : src/nodary/confusables_generated.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = ROOT / "data" / "uts39" / "confusables.txt"
VERSION_FILE = ROOT / "data" / "uts39" / "VERSION"
OUTPUT_FILE = ROOT / "src" / "nodary" / "confusables_generated.py"

_LINE_RE = re.compile(
    r"^([0-9A-Fa-f][0-9A-Fa-f ]*?)"  # source codepoint(s)
    r"\s*;\s*"
    r"([0-9A-Fa-f][0-9A-Fa-f ]*?)"  # target codepoint(s)
    r"\s*;\s*"
    r"(\w+)"  # type (MA, etc.)
)


def _hex_to_str(hex_str: str) -> str:
    """Convert space-separated hex codepoints to a Python string."""
    return "".join(chr(int(cp, 16)) for cp in hex_str.split())


def parse_confusables(path: Path) -> dict[str, str]:
    """Parse confusables.txt into {source_char: target_string}.

    Since skeleton() lowercases input before applying the map, we store
    lowercased keys and lowercased targets so that e.g. '0' -> 'o' (not 'O')
    and regular 'o' stays 'o', producing a collision.
    """
    mapping: dict[str, str] = {}
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            m = _LINE_RE.match(line)
            if not m:
                continue
            src_hex, tgt_hex, _typ = m.group(1), m.group(2), m.group(3)
            # Only map single-codepoint sources (multi-codepoint sources
            # are sequences, not individual character confusions).
            src_cps = src_hex.split()
            if len(src_cps) != 1:
                continue
            src_char = _hex_to_str(src_hex)
            tgt_str = _hex_to_str(tgt_hex)
            # Lowercase both sides to match skeleton()'s pre-lowercasing.
            src_key = src_char.lower()
            tgt_val = tgt_str.lower()
            # Skip identity mappings (source == target after lowering).
            if src_key == tgt_val:
                continue
            mapping[src_key] = tgt_val
    return mapping


def generate_module(mapping: dict[str, str], version: str) -> str:
    """Render the Python module source."""
    lines = [
        '"""Auto-generated from UTS #39 confusables.txt — DO NOT EDIT.',
        f"Unicode version: {version}",
        f"Total mappings: {len(mapping)}",
        "",
        "Generated by: scripts/generate_confusables.py",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "CONFUSABLES_MAP: dict[str, str] = {",
    ]
    for src in sorted(mapping, key=ord):
        tgt = mapping[src]
        src_repr = repr(src)
        tgt_repr = repr(tgt)
        lines.append(f"    {src_repr}: {tgt_repr},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not DATA_FILE.exists():
        print(f"ERROR: {DATA_FILE} not found. Vendor the data first.", file=sys.stderr)
        sys.exit(1)
    if not VERSION_FILE.exists():
        print(f"ERROR: {VERSION_FILE} not found.", file=sys.stderr)
        sys.exit(1)

    version = VERSION_FILE.read_text().strip()
    mapping = parse_confusables(DATA_FILE)
    source = generate_module(mapping, version)
    OUTPUT_FILE.write_text(source, encoding="utf-8")
    print(
        f"Wrote {len(mapping)} confusable mappings to {OUTPUT_FILE} "
        f"(Unicode {version})"
    )


if __name__ == "__main__":
    main()
